---
# Spring app configs
spring:
  application:
    name: airport-reservation-system
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # Datasource Configs
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;
    username: test
    password: pass123
    driver-class-name: org.h2.Driver
  sql:
    init:
      platform: h2
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  
  # RabbitMQ configs
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

# Server config
server:
  port: 8080

# Hibernate
dialect: org.hibernate.dialect.H2Dialect

# Management Endpoints config
management:
  server:
    port: 9000
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always

# Application Info
info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      profile: ${spring.profiles.active}

# Security
security:
  jwt:
    token:
      secret-key: secret-key
      # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds
      expire-length: 300000
