---
# Development profile configuration
server:
  servlet:
    context-path: /airport-reservation-system/dev

# H2 Database Configuration
spring:
  datasource:
    url: jdbc:h2:mem:airport-system-db;DB_CLOSE_DELAY=-1;
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: h2
  h2:
    console:
      enabled: true
      path: /h2-console

# RabbitMQ Configuration (commented out by default in dev)
# spring:
#   rabbitmq:
#     host: 127.0.0.1
#     port: 5672
#     username: guest
#     password: guest
