# Common application configuration
# Database configuration is in profile-specific files (e.g., application-test.yml)

spring:
  application:
    name: airport-reservation-system
  profiles:
    active: test

# Common application properties
app:
  version: 1.0.0
  
# Logging configuration (can be overridden in profile-specific configs)
logging:
  level:
    root: INFO
    com.sakinr.airportreservationsystem: INFO

# Default server configuration
server:
  port: 8080
    
# Common security configuration (can be overridden in profile-specific configs)
security:
  jwt:
    token:
      secret-key: ${JWT_SECRET:default-jwt-secret-key-1234567890}
      expire-length: 86400000  # 24 hours in milliseconds
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
  config:
    activate:
      on-profile: default
  devtools:
    restart:
      enabled: true

# Management endpoints (common for all profiles)
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# Application Info (common for all profiles)
info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@

