# Development profile configuration
spring:
  config:
    activate:
      on-profile: dev

  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:airport-system-db;DB_CLOSE_DELAY=-1;
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

# Development Server Configuration
server:
  port: 8080
  servlet:
    context-path: /airport-reservation-system/dev

# RabbitMQ Configuration (local development)
# Uncomment and configure as needed
# spring:
#   rabbitmq:
#     host: localhost
#     port: 5672
#     username: guest
#     password: guest

# Logging configuration for development
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.sakinr.airportreservationsystem: DEBUG
