# Common application configuration (shared across all profiles)
spring:
  application:
    name: airport-reservation-system
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
  config:
    activate:
      on-profile: default
  devtools:
    restart:
      enabled: true

# Management endpoints (common for all profiles)
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# Application Info (common for all profiles)
info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@

# Security (common for all profiles)
security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 300000  # 5 minutes in milliseconds
